// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: examples/shared/shared.proto

package example_shared

import (
	_ "bitbucket.org/holdex/go-proto-validators"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *InnerInnerMessage) Validate() error {
	return nil
}
